### ISSUE TITLE
[Doc] Add install link for Adblock Warning Removal List

### ISSUE THREAD

**Issue by mat41997** [AdBlockProtector2/AdBlockProtector2#2]
pleas add this link
``href="abp:subscribe?location=https://easylist-downloads.adblockplus.org/antiadblockfilters.txt&title=Adblock_Warning_Removal_List"``

to this site in step 1
https://adblockprotector2.github.io/AdBlockProtector2/
![2017-11-18 16_15_52-adblock protector 2](https://user-images.githubusercontent.com/5884000/32981915-c7786538-cc7b-11e7-9082-7d1bef084c60.png)

i believe this is be a most usefull

**Comment by mat41997** [comment]
and the same as this site
https://jspenguin2017.github.io/uBlockProtector/
![2017-11-18 16_20_50-ublock protector](https://user-images.githubusercontent.com/5884000/32981949-85103bc0-cc7c-11e7-8213-c4222df8ff26.png)

**Comment by jspenguin2017** [comment]
I thought it's in every adblocker already?

**Comment by mat41997** [comment]
@jspenguin2017 not enabled an in default
![2017-11-18 20_26_18-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/32984045-cdcf9bae-cc9e-11e7-9c29-0c32863ac975.png)
this link activate this option

**Comment by jspenguin2017** [comment]
Hum, I'll consider it.

**Comment by jspenguin2017** [comment]
This is resolved upstream, I'll fix it here after a working prototype for AdBlock / ABP is ready.
