### ISSUE TITLE
[Question/Suggestion] AdBlockProtector2 for Pale Moon

### ISSUE THREAD

**Issue by graciecat** [AdBlockProtector2/AdBlockProtector2#7]
I notice on your [announcement page](https://adblockprotector2.github.io/AdBlockProtector2/) that you plan to make your extension for Chromium, Opera, Quantum, and Edge. I would like to ask you to also please consider also making a version for [Pale Moon](http://www.palemoon.org/technical.shtml), a fork of Firefox with [significant differences](http://www.palemoon.org/technical.shtml#Firefox_Differences), including continued support for XUL/XPCOM & bootstrap. The Pale Moon community was saddened by the discontinuance of AAK-Cont, and we would thrilled if you could make what I am sure will be an excellent add-on available to us.

**Comment by jspenguin2017** [comment]
I have no plan in supporting legacy browsers. Sorry.

**Comment by mat41997** [comment]
@graciecat try it waterfox
https://www.waterfoxproject.org/

**Comment by Sa-Ja-Di** [comment]
no support for the new Chrome garbage extension technology makes another browser still no legacy product.

**Comment by jspenguin2017** [comment]
Pale moon is legacy, the new browser is called Basilisk. I might add support for Basilisk, but not now. 
If you still love the old technology then the fork button is there.
