### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by davidhedlund** [AdBlockProtector2/AdBlockProtector2#8]
https://adblockprotector2.github.io/AdBlockProtector2/ says

> Quantum (formerly Firefox) (COMING SOON!)

I suggest that you change the text because Firefox has not been renamed to Quantum. Firefox Quantum is the code name for Firefox 57.

**Comment by jspenguin2017** [comment]
I will keep it as is to emphasize that I will only support Firefox Quantum and not the old Firefox.

**Comment by davidhedlund** [comment]
@jspenguin2017 I get your point, but why not just change it to this?:
> Firefox Quantum (COMING SOON!)

**Comment by jspenguin2017** [comment]
Meh, I'm not going to make ABR2 after all.

**Comment by davidhedlund** [comment]
@jspenguin2017 Thanks, I see that you're working on [https://github.com/NanoAdblocker Nano Adblocker].
